---
- name: restart ipsec
  service: name=ipsec state=restarted
  sudo: yes
- name: restart xl2tpd
  service: name=xl2tpd state=restarted
  sudo: yes
- name: reload sysctl
  #command: "sysctl -p /etc/sysctl.conf"
  command: "sysctl -p"
  sudo: yes
